apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        component: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: {{ .Chart.Name }}
                  name: database-url
            - name: AWS_BUCKET
              value: {{ .Values.aws.bucket }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKeys }}
            - name: POOL_SIZE
              value: "{{ .Values.database.poolSize }}"
            - name: SECRET_KEY_BASE
              value: {{ .Values.secretKeyBase }}
            - name: PHX_HOST
              value: {{ .Values.localhost }}