name: Deploy GKE

on: pull_request

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_REGION: ${{ secrets.GKE_REGION }}
  IMAGE: ${{ secrets.APP }}
  HELM_PROJECT: ${{ secrets.HELM_PROJECT }}
  NAMESPACE: ${{ secrets.NAMESPACE }}

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: 'google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7'
       with:
          version: 'latest'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
     - run: |-
          gcloud --quiet auth configure-docker
     - uses: 'google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e'
       with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}
          credentials: ${{ secrets.GKE_SA_KEY }}
    #  - run: |-
    #       gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION" --project "$PROJECT_ID"
     - name: Build docker IMAGE
       run: |-
        docker pull "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" > /dev/null || docker build -t "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" .
     - name: Push docker image
       run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
     - name: Deploy Helm Chart
       working-directory: "./helm"
       run: |-
        pwd
        helm dependency update
        helm \
        -n "$NAMESPACE" \
        upgrade "$HELM_PROJECT" \
        ./ \
        --wait \
        --reuse-values \
        --set image.repository="gcr.io/$PROJECT_ID/$IMAGE",image.tag="$GITHUB_SHA"